use_frameworks!

platform :ios, '10.0'

target 'VideoQuickSeeking_Example' do
  pod 'VideoQuickSeeking', :path => '../'

  target 'VideoQuickSeeking_Tests' do
    inherit! :search_paths

    
  end
end
